num_agents: 4
map_name: open_narrow_obs
gym_root: /opt/f1tenth_gym
rate_hz: 50
cmd_timeout: 2.0
render: false
dynamics: st
initial_poses:
- - 5.028413
  - -1.5
  - 0.0
- - 5.028413
  - -0.5
  - 0.0
- - 5.028413
  - 0.5
  - 0.0
- - 5.028413
  - 1.5
  - 0.0
goal_x: 60.335858
goal_y: -83.65055
goal_yaw: -1.0076
goal_delay_s: 5.0
goal_republish_period_s: 2.0
auto_publish_goal: true
tb_num: 4
episode_end_mode: map_goal
episode_timeout_s: 900.0
