"""ROS / Gazebo target for the DEFORM baseline.

Emits, under ``out_root/<name>_<n>agents/``:

* ``map/<name>.pgm + .yaml``      map_server occupancy grid (same pixels)
* ``worlds/<name>.world``          Gazebo SDF: every wall segment of the traced
                                   corridor polygon as a static box
* ``config/bridge_params.yaml``    spawn/goal for the f1tenth bridge (DEFORM's
                                   planner + f1tenth plant)
* ``config/frm_shape.yaml``        DEFORM formation file for N robots
* ``config/metrics.yaml``          what the ffbench ROS metrics node needs
* ``launch/deform_f1tenth.launch`` bridge mode (f1tenth backend inside ROS)
* ``launch/deform_native.launch``  Gazebo + TurtleBot3 mode (native backend)
* ``track/`` (f1tenth format)      so the bridge can load the map by name

Spawn and goal come from the shared protocol so DEFORM starts exactly where
ORCA / NMPC / leader-follower start.
"""
from __future__ import annotations

import math
import pathlib
import shutil

import numpy as np
import yaml

from ffbench.maps.source import MapSource
from ffbench.maps.targets.f1tenth import write_f1tenth


def _world_sdf(name: str, rects: np.ndarray, wall_height: float) -> str:
    links = []
    for i, (cx, cy, w, h, th) in enumerate(rects):
        links.append(f"""
      <link name="wall_{i}">
        <pose>{cx:.4f} {cy:.4f} {wall_height / 2:.4f} 0 0 {th:.5f}</pose>
        <collision name="c"><geometry><box><size>{w:.4f} {h:.4f} {wall_height:.4f}</size></box></geometry></collision>
        <visual name="v"><geometry><box><size>{w:.4f} {h:.4f} {wall_height:.4f}</size></box></geometry>
          <material><ambient>0.35 0.35 0.35 1</ambient><diffuse>0.5 0.5 0.5 1</diffuse></material></visual>
      </link>""")
    return f"""<?xml version="1.0"?>
<sdf version="1.6">
  <world name="{name}">
    <include><uri>model://ground_plane</uri></include>
    <include><uri>model://sun</uri></include>
    <physics type="ode"><real_time_update_rate>1000</real_time_update_rate><max_step_size>0.001</max_step_size></physics>
    <model name="corridor_walls">
      <static>true</static>{''.join(links)}
    </model>
  </world>
</sdf>
"""


def _planner_includes(n: int) -> str:
    other = max(1, min(2, n - 1))
    parts = []
    for i in range(n):
        parts.append(f"""
  <rosparam param="/tb_{i}_manager_node/grid_map/obstacles_inflation">0.0</rosparam>
  <rosparam param="/tb_{i}_manager_node/grid_map/depth_filter_tolerance">0.25</rosparam>
  <include file="$(find plan_manager)/launch/one_run.xml">
    <arg name="tb_id" value="{i}"/>
    <arg name="tb_num" value="{n}"/>
    <arg name="frm_type" value="{n}"/>
    <arg name="other_num_in_opti" value="{other}"/>
  </include>""")
    return "".join(parts)


def _bridge_launch(name: str, n: int, poses, goal, end_mode: str, timeout_s: float,
                   dynamics: str) -> str:
    pose_yaml = "\n".join(f"      - [{x:.6f}, {y:.6f}, {th:.4f}]" for x, y, th in poses)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- generated by ffbench: DEFORM planner driving the f1tenth plant (bridge mode) -->
<launch>
  <arg name="target_episodes" default="1"/>
  <arg name="episode_timeout_s" default="{timeout_s:.0f}"/>
  <arg name="render" default="false"/>
  <arg name="dynamics" default="{dynamics}"/>

  <node name="f1tenth_bridge" pkg="f1tenth_deform_bridge" type="f1tenth_bridge_node.py"
        output="screen" required="true">
    <rosparam file="/root/DEFORM/src/utility/f1tenth_deform_bridge/config/bridge_params.yaml" command="load"/>
    <param name="num_agents" value="{n}"/>
    <param name="map_name" value="{name}"/>
    <param name="tb_num" value="{n}"/>
    <param name="render" value="$(arg render)"/>
    <param name="dynamics" value="$(arg dynamics)"/>
    <param name="auto_publish_goal" value="true"/>
    <param name="goal_republish_period_s" value="2.0"/>
    <param name="episode_end_mode" value="{end_mode}"/>
    <param name="goal_x" value="{goal[0]:.6f}"/>
    <param name="goal_y" value="{goal[1]:.6f}"/>
    <param name="goal_yaw" value="{goal[2]:.4f}"/>
    <param name="goal_delay_s" value="10.0"/>
    <param name="cmd_timeout" value="2.0"/>
    <param name="target_episodes" value="$(arg target_episodes)"/>
    <param name="episode_timeout_s" value="$(arg episode_timeout_s)"/>
    <rosparam param="initial_poses">
{pose_yaml}
    </rosparam>
  </node>
{_planner_includes(n)}
</launch>
"""


def _native_launch(name: str, n: int, poses, goal, timeout_s: float, robot_model: str) -> str:
    spawns = []
    for i, (x, y, th) in enumerate(poses):
        spawns.append(f"""
  <include file="$(find multi_turtlebot3_simulation)/launch/one_robot.xml">
    <arg name="model" value="$(arg model)"/>
    <arg name="tb3_name" value="tb_{i}"/>
    <arg name="robot_x_pos" value="{x:.4f}"/>
    <arg name="robot_y_pos" value="{y:.4f}"/>
    <arg name="robot_z_pos" value="0.0"/>
    <arg name="robot_yaw" value="{th:.4f}"/>
  </include>""")
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- generated by ffbench: DEFORM in its native Gazebo + TurtleBot3 setup.
     Robots are spawned by DEFORM's own multi_turtlebot3_simulation/one_robot.xml
     (TurtleBot3 + RealSense D435 publishing /tb_<i>/camera/depth/image_raw,
     which DEFORM's drone_detect filters into .../image_filter for grid_map). -->
<launch>
  <arg name="model" default="{robot_model}"/>
  <arg name="gui" default="false"/>
  <arg name="world" default="$(dirname)/../worlds/{name}.world"/>
  <arg name="episode_timeout_s" default="{timeout_s:.0f}"/>

  <include file="$(find gazebo_ros)/launch/empty_world.launch">
    <arg name="world_name" value="$(arg world)"/>
    <arg name="paused" value="false"/>
    <arg name="use_sim_time" value="true"/>
    <arg name="gui" value="$(arg gui)"/>
    <arg name="headless" value="true"/>
    <arg name="debug" value="false"/>
  </include>

  <node pkg="map_server" type="map_server" name="map_server" args="$(dirname)/../map/{name}.yaml"/>
{''.join(spawns)}

  <!-- goal: same waypoint every backend uses as the zone exit -->
  <node pkg="f1tenth_deform_bridge" type="goal_publisher.py" name="goal_publisher" output="screen">
    <param name="goal_x" value="{goal[0]:.6f}"/>
    <param name="goal_y" value="{goal[1]:.6f}"/>
    <param name="goal_yaw" value="{goal[2]:.4f}"/>
    <param name="tb_num" value="{n}"/>
    <param name="goal_delay_s" value="10.0"/>
  </node>

  <!-- metrics: ffbench_ros/scripts/metrics_node.py is started next to this
       launch by the ffbench driver (same FullRunMetrics as every backend) -->
{_planner_includes(n)}
</launch>
"""


def _frm_shape(n: int, spacing: float) -> dict:
    # initial: the abreast rank the protocol spawns (y across the corridor);
    # desired: same rank -- DEFORM may collapse it as the corridor demands.
    half = (n - 1) / 2.0
    init = {f"vehicle_pos_{i + 1}": {"x": 0.0, "y": round((i - half) * spacing, 4)}
            for i in range(n)}
    return {"task_type": 1, "vehicle_number": n,
            "initial_shape_positions": init,
            "desired_shape_positions": dict(init)}


def write_ros(src: MapSource, out_root, n_agents: int = 4, poses=None, goal=None,
              end_mode: str = "narrow_clear", timeout_s: float = 300.0,
              wall_thickness_m: float = 0.3, wall_height_m: float = 0.5,
              robot_model: str = "burger", formation_spacing: float = 0.6,
              dynamics: str = "st", zone_half_wp: int = 8,
              ref_centerline=None, collision_thresh: float | None = None) -> pathlib.Path:
    from gcbf_baseline.corridor_geom import wall_rects
    d = pathlib.Path(out_root) / f"{src.name}_{n_agents}agents"
    for sub in ("map", "worlds", "config", "launch"):
        (d / sub).mkdir(parents=True, exist_ok=True)

    # map_server files (same pixel image, current scale)
    shutil.copyfile(src.image_path, d / "map" / f"{src.name}.pgm")
    with open(d / "map" / f"{src.name}.yaml", "w") as f:
        yaml.safe_dump({"image": f"{src.name}.pgm", "resolution": float(src.resolution),
                        "origin": [float(src.origin[0]), float(src.origin[1]), 0.0],
                        "negate": 0, "occupied_thresh": 0.45, "free_thresh": 0.196},
                       f, sort_keys=False)

    # Gazebo world from the corridor polygon
    geom = src.corridor_geom()
    rects = wall_rects(geom, geom.window(), thickness_m=wall_thickness_m, reach_m=1e9)
    (d / "worlds" / f"{src.name}.world").write_text(
        _world_sdf(src.name, rects, wall_height_m * src.scale / max(src.scale, 1e-9)))

    # f1tenth-format track for the bridge (mounted at /opt/f1tenth_gym/maps/<name>)
    write_f1tenth(src, d / "track", force=True)

    if poses is None:
        wp = src.nearest_wp(*src.narrow_xy)
        t = src.tangent(wp)
        th = math.atan2(t[1], t[0])
        nrm = np.array([-t[1], t[0]])
        base = np.array(src.narrow_xy) - t * 14.0 * src.scale
        half = (n_agents - 1) / 2.0
        poses = [(*(base + nrm * (i - half) * formation_spacing), th) for i in range(n_agents)]
    if goal is None:
        wp = src.nearest_wp(*src.narrow_xy)
        t = src.tangent(wp)
        g = np.array(src.narrow_xy) + t * 20.0 * src.scale
        goal = (float(g[0]), float(g[1]), math.atan2(t[1], t[0]))

    with open(d / "config" / "bridge_params.yaml", "w") as f:
        yaml.safe_dump({
            "num_agents": n_agents, "map_name": src.name, "gym_root": "/opt/f1tenth_gym",
            "rate_hz": 50, "cmd_timeout": 2.0, "render": False, "dynamics": dynamics,
            "initial_poses": [[round(float(x), 6), round(float(y), 6), round(float(th), 4)]
                              for x, y, th in poses],
            "goal_x": round(float(goal[0]), 6), "goal_y": round(float(goal[1]), 6),
            "goal_yaw": round(float(goal[2]), 4), "goal_delay_s": 5.0,
            "goal_republish_period_s": 2.0, "auto_publish_goal": True, "tb_num": n_agents,
            "episode_end_mode": end_mode, "episode_timeout_s": float(timeout_s),
        }, f, sort_keys=False)
    with open(d / "config" / "frm_shape.yaml", "w") as f:
        yaml.safe_dump(_frm_shape(n_agents, formation_spacing), f, sort_keys=False)
    cl = np.asarray(ref_centerline if ref_centerline is not None else src.centerline)
    with open(d / "config" / "metrics.yaml", "w") as f:
        yaml.safe_dump({
            "map": src.name, "scale": float(src.scale),
            "centerline": cl.round(4).tolist(),
            "narrow_xy": [float(src.narrow_xy[0]), float(src.narrow_xy[1])],
            "gap_width_m": float(src.gap_width_m),
            "zone_half_width_wp": int(zone_half_wp),
            "collision_thresh_m": round(float(collision_thresh if collision_thresh else 0.5 * src.scale), 4),
            "goal": [float(goal[0]), float(goal[1])],
        }, f, sort_keys=False)
    (d / "launch" / "deform_f1tenth.launch").write_text(
        _bridge_launch(src.name, n_agents, poses, goal, end_mode, timeout_s, dynamics))
    (d / "launch" / "deform_native.launch").write_text(
        _native_launch(src.name, n_agents, poses, goal, timeout_s, robot_model))

    # the ROS metrics package travels with the generated bundle
    pkg_src = pathlib.Path(__file__).resolve().parents[2] / "ros" / "ffbench_ros"
    if pkg_src.exists():
        if (d / "ffbench_ros").exists():
            shutil.rmtree(d / "ffbench_ros")
        shutil.copytree(pkg_src, d / "ffbench_ros")
        shutil.copyfile(pathlib.Path(__file__).resolve().parents[3] / "baselines" / "eval_metrics.py",
                        d / "ffbench_ros" / "scripts" / "eval_metrics.py")
    return d
